name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Publish Screensaver
      run: |
        cd MosaicScreensaver
        dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true
        Rename-Item -Path "bin\Release\net6.0-windows\win-x64\publish\MosaicScreensaver.exe" -NewName "MosaicScreensaver_Standalone.scr"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: MosaicScreensaver/bin/Release/net6.0-windows/win-x64/publish/MosaicScreensaver_Standalone.scr
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
